type: object
properties:
  projectId:
    type: integer
    format: int64
  projectNumber:
    type: string
  projectName:
    type: string
  projectDescription:
    type: string
  projectStartDate:
    type: string
    format: date
  projectEndDate:
    type: string
    format: date
  projectStatus:
    type: string
  projectStatusCode:
    type: string
  projectTypeId:
    type: integer
    format: int64
  projectType:
    type: string
  businessUnitName:
    type: string
  projectUnitId:
    type: integer
    format: int64
  workTypeId:
    type: integer
    format: int64
  capitalCostTypeCode:
    type: string
  owningOrganizationName:
    type: string
  projectManagerName:
    type: string
  projectCurrencyCode:
    type: string
  sourceTemplateName:
    type: string
  legalEntityName:
    type: string
